# Generated by Django 5.0.2 on 2024-06-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shippingaddress_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
