# Generated by Django 5.0.2 on 2024-06-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_options_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adress2',
            new_name='address2',
        ),
    ]
