# Generated by Django 5.0.2 on 2024-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
