# Generated by Django 5.0.2 on 2024-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Smartwatch', 'Smartwatch'), ('Headphone', 'Headphone'), ('Power Bank', 'Power Bank'), ('Kitchen Accesories', 'Kitchen Accesories'), ('Fan', 'Fan')], max_length=20),
        ),
    ]
